"""create cases sides contacts tables

Revision ID: 88da53083a02
Revises: 
Create Date: 2026-09-25 14:40:18.493913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88da53083a02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=64), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=False),
    sa.Column('case_type', sa.String(length=16), nullable=True),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=False)
    op.create_index(op.f('ix_cases_guid'), 'cases', ['guid'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_inn'), 'contacts', ['inn'], unique=True)
    op.create_table('sides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sides_case_id'), 'sides', ['case_id'], unique=False)
    op.create_index('ix_sides_case_id_role', 'sides', ['case_id', 'role'], unique=False)
    op.create_index(op.f('ix_sides_inn'), 'sides', ['inn'], unique=False)
    op.create_index('ix_sides_inn_role', 'sides', ['inn', 'role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sides_inn_role', table_name='sides')
    op.drop_index(op.f('ix_sides_inn'), table_name='sides')
    op.drop_index('ix_sides_case_id_role', table_name='sides')
    op.drop_index(op.f('ix_sides_case_id'), table_name='sides')
    op.drop_table('sides')
    op.drop_index(op.f('ix_contacts_inn'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_cases_guid'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
